on:
  push:

jobs: 
  expression-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name:  General build 
        run: echo "This is a general build step that runs on every push."

      - name: Conditional Deployment
        if: github.event_name == 'pull_request'
        run: echo "Pull-request has been done"
