on:
    schedule:
        - cron: "20 21 * * *"
    workflow_dispatch:

jobs:
    daily_task:
      runs-on: ubuntu-22.04
      steps:
          - name: Print Message
            run: echo "Hello,world"
