on:
    workflow_dispatch:
        inputs:
          environment:
              description: "choose environment"
              required: true
              default: "staging"
              type: choice
              options:
                - staging
                - production
jobs:
    daily_task:
      runs-on: ubuntu-22.04
      steps:
          - name: Deployment Message
            run: echo "Deploying The Application in ${{inputs.environment}}"
